language: csharp
solution: UnitOfWork.NET.sln
install:
  - nuget restore UnitOfWork.NET.sln
  - sudo apt-get install nunit-console
script:
  - xbuild /p:Configuration=Release UnitOfWork.NET.sln
  - nunit-console ./Caelan.Frameworks.BIZ.NUnit/bin/Release/UnitOfWork.NET.NUnit.dll
